### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by alexrazv** [sintaxi/dbox#63]
Hi,

The exception occures when I invoke a function from Client

The screenshot:
http://screencast.com/t/YIRjMVi20jiS

The text:

C:!Hg\timetracker\node_modules\dbox\lib\helpers.js:25
      var rx = RegExp("^" + scopePath, "i")
               ^
SyntaxError: Invalid regular expression: /^\/: \ at end of pattern
    at new RegExp (unknown source)
    at RegExp (unknown source)
    at Object.module.exports.parseJSON (C:!Hg\timetracker\node_modules\dbox\lib\helpers.js:25:16)
    at Request.exports.app.client.account [as _callback](C:!Hgtimetrackernode_modulesdboxlibdbox.js:64:60)
    at Request.init.self.callback (C:!Hg\timetracker\node_modules\dbox\node_modules\request\main.js:119:22)
    at Request.<anonymous> (C:!Hg\timetracker\node_modules\dbox\node_modules\request\main.js:525:16)
    at Request.EventEmitter.emit (events.js:96:17)
    at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (C:!Hg\timetracker\node_modules\dbox\node_modules\request\main.js:484:14
)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:366:10)
DEBUG: Program node app.js exited with code 1

**Comment by arash-sadr** [comment]
Hello guys,

No body managed to fix this issue? any updates? ;) 

The fix I did for myself is replacing the "\" with "/"... as below in helper.js line 22 to 24

22      var sPath = path.join("/", scope)
23      var scopePath = sPath.replace("\\", "/")
24      var rx = RegExp("^" + scopePath, "i")

Cheers

**Comment by ashfaq-unstoppable** [comment]
replace this in helper.js
var scopePath = path.join("/", scope)
to
var scopePath = path.join("/", scope).replace("\\", "/");
